# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on: [push]
jobs:
  jobs:
    install-and-test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - uses: actions/checkout@master

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install
          run: yarn install --frozen-lockfile

        - name: Build
          run: yarn build

          env:
            CI: true
